apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "datafusionx-commercial.fullname" . }}-postgres
  labels:
    {{- include "datafusionx-commercial.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "datafusionx-commercial.fullname" . }}-licenses
  labels:
    {{- include "datafusionx-commercial.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
