apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datafusionx-commercial.fullname" . }}-secret
  labels:
    {{- include "datafusionx-commercial.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  JWT_SECRET_KEY: {{ .Values.secrets.jwtSecretKey | quote }}
  ENCRYPTION_SECRET_KEY: {{ .Values.secrets.encryptionSecretKey | quote }}
  LICENSE_PUBLIC_KEY: {{ .Values.secrets.licensePublicKey | quote }}
  LICENSE_CUSTOMER_ID: {{ .Values.secrets.licenseCustomerId | quote }}
  LICENSE_DEPLOYMENT_ID: {{ .Values.secrets.licenseDeploymentId | quote }}
  COMMERCIAL_INTEGRITY_PUBLIC_KEY: {{ .Values.secrets.commercialIntegrityPublicKey | quote }}
